version: '3'
services:
  # app:
  #   container_name: docker-node-mongo
  #   restart: always
  #   build: .
  #   ports:
  #     - '8080:3000'
  #   external_links:
  #     - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./temp/data/db:/data/db
  redis:
    image: redis
    ports: 
      - "6379:6379"
